<?php

/**
 * Implements hook_preprocess_node().
 */
function path_alias_arg_preprocess_node(array &$variables) {
  $node = $variables['node'];
  if ($node->bundle() === 'filtered_page') {
    $variables['#cache']['contexts'][] = 'node_arguments';
    $request = \Drupal::request();

    // Set path_alias_arguments as node variables.
    $variables['path_alias_arguments'] = $request->attributes->get('path_alias_arguments');
  }
}
