<?php

namespace Drupal\alias_subpaths_node\Plugin\ArgumentProcessor;

use Drupal\alias_subpaths\Plugin\ArgumentProcessorBase;
use Drupal\alias_subpaths\Plugin\Attribute\ArgumentProcessor;

/**
 * Provides an ArgumentProcessor for nodes.
 */
#[ArgumentProcessor(
  id: 'node', route_name: 'entity.node.canonical',
)]
class NodeArgumentProcessor extends ArgumentProcessorBase {

  public function hasArguments() {
    return parent::hasArguments(); //@TODO: Change the autogenerated stub
  }

  public function process() {
    $args = $this->contextManager->getContextBag();
    $node = $this->currentRouteMatch->getParameter('node');
    //@TODO:
  }

}
